In [10]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# 导入数据函数
def loadData(filename):
    data = pd.read_csv(filename, sep='\s+', header=None)
    data = data.as_matrix()
    col, row = data.shape
    X = np.c_[np.ones((col, 1)), data[:, 0: row-1]]
    Y = data[:, row-1:row]
    return X, Y
# 生成数据函数
def generateData():
    x = np.random.uniform(-1, 1, 3)
    y = np.sign(x)
    y[y == 0] = -1
    prop = np.random.uniform(0, 1, 3)
    y[prop >= 0.8] *= -1
    return x, y
# 单维度决策树桩算法
def decision_stump(X, Y):
    theta = np.sort(X)
    num = len(theta)
    Xtemp = np.tile(X, (num, 1))
    ttemp = np.tile(np.reshape(theta, (num, 1)), (1, num))
    ypred = np.sign(Xtemp - ttemp)
    ypred[ypred == 0] = -1
    err = np.sum(ypred != Y, axis=1)
    if np.min(err) <= num-np.max(err):
        return 1, theta[np.argmin(err)], np.min(err)/num
    else:
        return -1, theta[np.argmax(err)], (num-np.max(err))/num
X, Y = generateData()
print(X)
theta = np.sort(X)
print('theta\n:',theta)
num = len(theta)
Xtemp = np.tile(X, (num, 1))
print('Xtemp:\n',Xtemp)
theta=np.reshape(theta, (num, 1))
ttemp = np.tile(theta, (1, num))  #copy 1 times and 3 row
print('ttemp:\n',ttemp)
ypred = np.sign(Xtemp - ttemp)
ypred[ypred == 0] = -1
print('ypred:\n',ypred)
print('y=\n',Y)
err = np.sum(ypred != Y, axis=1)
print('err:\n',err )
if np.min(err) <= num-np.max(err):
    print(1, theta[np.argmin(err)], np.min(err)/num)
else:
    print( -1, theta[np.argmax(err)], (num-np.max(err))/num)
print(np.argmin(err))

[ 0.46668159 -0.6634572  -0.20449132]
theta
: [-0.6634572  -0.20449132  0.46668159]
Xtemp:
 [[ 0.46668159 -0.6634572  -0.20449132]
 [ 0.46668159 -0.6634572  -0.20449132]
 [ 0.46668159 -0.6634572  -0.20449132]]
ttemp:
 [[-0.6634572  -0.6634572  -0.6634572 ]
 [-0.20449132 -0.20449132 -0.20449132]
 [ 0.46668159  0.46668159  0.46668159]]
ypred:
 [[ 1. -1.  1.]
 [ 1. -1. -1.]
 [-1. -1. -1.]]
y=
 [ 1.  1. -1.]
err:
 [2 1 2]
1 [-0.20449132] 0.3333333333333333
1


In [13]:
X, Y = loadData('data\hw2_train.dat')
#print(X[:,0:5])
row, col = X.shape
print('XSHAPE',len(X),X.shape)
err = np.zeros((col,)); s = np.zeros((col,)); theta = np.zeros((col,))
for i in range(3):
    s[i], theta[i], err[i] = decision_stump(X[:, i], Y[:, 0])
    print('theta',theta)
pos = np.argmin(err)

XSHAPE 100 (100, 10)
theta [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
theta [1.    3.875 0.    0.    0.    0.    0.    0.    0.    0.   ]
theta [ 1.     3.875 -3.39   0.     0.     0.     0.     0.     0.     0.   ]


c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
